apiVersion: v1
kind: Service
metadata:
  name: hello-java-service
spec:
  selector:
    app: hello-java
  type: NodePort
  ports:
    - port: 80           # Internal cluster port
      targetPort: 8080   # Port inside the container
      nodePort: 30007    # Exposed port on the node (must be in range 30000–32767)
