apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-java-deployment
  labels:
    app: hello-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-java
  template:
    metadata:
      labels:
        app: hello-java
    spec:
      containers:
        - name: hello-java-container
          image: mohamed1311990/hello-docker-java:latest
          ports:
            - containerPort: 8080
